### ISSUE TITLE
MSW not correctly bypassing requests made with @auth0/nextjs-auth0

### ISSUE THREAD

**Issue by StevenPewsey** [mswjs/msw#700]
## Describe the bug
I am trying to use MSW to mock some requests made in a nextjs application that is using [@auth0/nextjs-auth0](https://github.com/auth0/nextjs-auth0) to handle the authentication flow.

I want MSW to bypass the requests made as part of that authentication flow, however instead I am getting the following error when trying to login (through `http://localhost:3000/api/auth/login`):

```
[MSW] Warning: captured a request without a matching request handler:

  • GET https://abcga.eu.auth0.com/.well-known/oauth-authorization-server

If you still wish to intercept this unhandled request, please create a request handler for it.
Read more: https://mswjs.io/docs/getting-started/mocks
RequestError: connect ECONNREFUSED 127.0.0.1:443
    at ClientRequestOverride.<anonymous> (/Users/steve.pewsey/Documents/Personal/Projects/abcga-ui/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequestOverride.emit (events.js:327:22)
    at ClientRequestOverride.origin.emit (/Users/steve.pewsey/Documents/Personal/Projects/abcga-ui/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at ClientRequest.<anonymous> (/Users/steve.pewsey/Documents/Personal/Projects/abcga-ui/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/createClientRequestOverride.js:317:39)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  code: 'ECONNREFUSED',
  timings: {
    start: 1618657265514,
    socket: 1618657265514,
    lookup: 1618657265514,
    connect: 1618657265514,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1618657265525,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 0,
      tcp: 0,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 11
    }
  }
}
```

It seems that for some reason it is trying to make a request to `https://localhost`. I am not sure why this is happening, when MSW is disabled everything works as expected, so I can only assume that MSW is at fault.

## Environment

- `msw: 0.28.1`
- `nodejs: 14.16.1`
- `npm: 6.14.12`

## To Reproduce
1. Clone MSW NextJS [example](https://github.com/vercel/next.js/tree/canary/examples/with-msw)
2. Combine this with the Auth0 NextJs [basic setup](https://github.com/auth0/nextjs-auth0)
3. Start dev server
4. Go to `http://localhost:3000/api/auth/login`
5. See error (for some reason at times this error can be a bit non-deterministic and I can process to auth0, but when it redirects me back to my application I get the same error).

## Expected behavior
Be redirected to auth0 to login, and then be redirected back to the application.

Thanks! Happy to provide more details if required.

**Comment by androa** [comment]
I'm also experiencing this, but not with the Auth0 client, but `openid-client` and `passport`. Not able to figure out exactly where this happens, but it seems to be somewhere inside `got`.

It seems to be quite similar to mswjs/msw#486.

There is also a lot of similar issues at sindresorhus/got#1463 sindresorhus/got#1429 sindresorhus/got#982 sindresorhus/got#951.

The cause of all these seems to be the monkey-patching of node's request object.

**Comment by kettanaito** [comment]
The issue is in the request options passed to the original `https.request` in this case. Here's the passed object:

```js
{
  method: 'GET',
  retry: {
    calculateDelay: [Function: calculateDelay],
    limit: 0,
    methods: [Array],
    statusCodes: [Array],
    errorCodes: [Array],
    maxRetryAfter: Infinity
  },
  headers: {
    'user-agent': 'nextjs-auth0/1.4.2',
    'auth0-client': 'REDACTED',
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br'
  },
  hooks: {
    init: [],
    beforeRequest: [],
    beforeRedirect: [],
    beforeRetry: [],
    beforeError: [],
    afterResponse: []
  },
  cache: undefined,
  dnsCache: undefined,
  decompress: true,
  throwHttpErrors: false,
  followRedirect: false,
  isStream: false,
  responseType: 'json',
  resolveBodyOnly: false,
  maxRedirects: 10,
  prefixUrl: '',
  methodRewriting: true,
  ignoreInvalidCookies: false,
  http2: false,
  allowGetBody: false,
  https: undefined,
  pagination: {
    transform: [Function: transform],
    paginate: [Function: paginate],
    filter: [Function: filter],
    shouldContinue: [Function: shouldContinue],
    countLimit: Infinity,
    backoff: 0,
    requestLimit: 10000,
    stackAllItems: true
  },
  parseJson: [Function: parseJson],
  stringifyJson: [Function: stringifyJson],
  cacheOptions: {},
  username: '',
  password: '',
  url: URL {
    href: 'https://REDACTED.auth0.com/.well-known/oauth-authorization-server',
    origin: 'https://REDACTED.auth0.com',
    protocol: 'https:',
    username: '',
    password: '',
    host: 'REDACTED.auth0.com',
    hostname: 'REDACTED.auth0.com',
    port: '',
    pathname: '/.well-known/oauth-authorization-server',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
  },
  shared: undefined,
  cacheHeuristic: undefined,
  immutableMinTimeToLive: undefined,
  ignoreCargoCult: undefined,
  protocol: 'https:'
}
```

Here's where that request options object is passed:

https://github.com/mswjs/interceptors/blob/175bb79007d85665caed3ed0816c713af21beb9f/src/interceptors/ClientRequest/createClientRequestOverride.ts#L276-L277

However, `https.request` doesn't accept the `url`/`uri` option in its request options:

```ts
type RequestOptions = http.RequestOptions & tls.SecureContextOptions & {
  rejectUnauthorized?: boolean; // Defaults to true
  servername?: string; // SNI TLS Extension
};

// http.RequestOptions
interface ClientRequestArgs {
  abort?: AbortSignal;
  protocol?: string | null;
  host?: string | null;
  hostname?: string | null;
  family?: number;
  port?: number | string | null;
  defaultPort?: number | string;
  localAddress?: string;
  socketPath?: string;
  /**
   * @default 8192
   */
  maxHeaderSize?: number;
  method?: string;
  path?: string | null;
  headers?: OutgoingHttpHeaders;
  auth?: string | null;
  agent?: Agent | boolean;
  _defaultAgent?: Agent;
  timeout?: number;
  setHost?: boolean;
  // https://github.com/nodejs/node/blob/master/lib/_http_client.js#L278
  createConnection?: (options: ClientRequestArgs, oncreate: (err: Error, socket: Socket) => void) => Socket;
}
```

Instead, its signature supports the URL as the first argument:

```ts
function request(url: string | URL, options: RequestOptions, callback?: (res: http.IncomingMessage) => void): http.ClientRequest;
```

So the original request call in @mswjs/interceptors should be rewritten to:

```diff
-request = pureMethod(options)
+request = pureMethod(options.url, options)
```

**Comment by kettanaito** [comment]
I can confirm that integrating the fix above fixes the issue and the auth0 flow functions as expected. Will provision the fix and the related tests and update the libraries.

**Comment by kettanaito** [comment]
The fix has been released in [0.30.1](https://github.com/mswjs/msw/releases/tag/v0.30.1). Could you please update and let me know if the issue is gone? Thanks.

**Comment by StevenPewsey** [comment]
> 
> 
> The fix has been released in [0.30.1](https://github.com/mswjs/msw/releases/tag/v0.30.1). Could you please update and let me know if the issue is gone? Thanks.

Yes I can confirm that the issue has been fixed. Thanks a lot!

**Comment by mct-dev** [comment]
FYI @kettanaito - I believe this problem (or something like it) is still occurring in new msw versions.  I am having the exact same issue described in [this Auth0 issue](https://github.com/auth0/nextjs-auth0/issues/606).  They link to this thread and the suggested resolution of **downgrading MSW** is what fixed the issue for me.  I am using axios and version `0.36.8` of MSW is a working version for me.  Newest version (`0.43.0` i think?) does not work.

**Comment by kettanaito** [comment]
Hey, @mct-dev. Thanks for letting me know. 

Please, do you have a reproduction repository where I can look into the issue you are experiencing? I think this one has been resolved, so maybe you're having a similar one. Let's double-check.

**Comment by mct-dev** [comment]
> Hey, @mct-dev. Thanks for letting me know.
> 
> Please, do you have a reproduction repository where I can look into the issue you are experiencing? I think this one has been resolved, so maybe you're having a similar one. Let's double-check.

I'll see if I can find some time to create a reproduction repo.  Might be tough though, especially since half the setup has to be done in your own auth0 environment.  For now, I guess I'll just have to use the old msw version...  :(

**Comment by mct-dev** [comment]
@kettanaito would it be possible to debug this using the repro steps in the related [Auth0 Issue](https://github.com/auth0/nextjs-auth0/issues/606)?  I would love to upgrade my MSW version...

**Comment by Nargonath** [comment]
Hey @kettanaito,

Following your previous message, we have the same problem as mentioned in this issue and we're using recent versions. I've created a repro here: https://github.com/Nargonath/repro-nextjs-auth0-msw. I created it yesterday so all dependencies should have the latest version. I added instructions in the README but if anything's missing please feel free to ask for it.

**Comment by kettanaito** [comment]
Thanks for a reproduction case, @Nargonath. I'm quite overwhelmed with work right now so I don't think I'll have time to look into this any time soon. Contributors are welcome ❤️ 

Meanwhile, feel free to revert to the latest version that's proven working with your setup.

**Comment by Nargonath** [comment]
Sure I understand. Thanks for letting me know. Not sure I'll have the time to look into the issue either, we'll see.
